[package]
name = "pi"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dev-dependencies]
winit = "0.26"
pollster = "0.2"
log = "0.4"
env_logger = "0.9"

[[example]]
name = "hello_winit"
path = "examples/hello_winit/main.rs"