[package]
name = "render_core"
version = "0.1.0"
authors = ["moyy <myy412001799@gmail.com>"]
edition = "2021"
description = "Renderer for PI Engine"
repository = "https://github.com/GaiaWorld/pi_render"
license = "MIT OR Apache-2.0"
keywords = ["pi"]

[features]
location=[]

[dependencies]
paste = "1.0"
pi_async = "0.2"
pi_async_graph = "0.2"
pi_graph = "0.1"
pi_hash = "0.1"
pi_map = "0.1"
pi_null = "0.1"
pi_ecs_macros = "0.1"
pi_share = "0.1"
pi_slotmap = "0.1"
async-trait = "0.1"
render_utils = { version = "0.1", path = "../render_utils" }
render_crevice = { version = "0.1", path = "../render_crevice", features = [
    "nalgebra",
] }
uuid = { version = "0.8", features = ["v4", "serde"] }
winit = "0.26"
anyhow = "1.0"
downcast-rs = "1.2"
futures = "0.3"
hex = "0.4"
log = "0.4"
naga = { version = "0.8", features = [
    "glsl-in",
    "spv-in",
    "spv-out",
    "wgsl-in",
    "wgsl-out",
] }
nalgebra = "0.30"
parry3d = "0.8"
once_cell = "1.4" # TODO: replace once_cell with std equivalent if/when this lands: https://github.com/rust-lang/rfcs/pull/2788
regex = "1.5"
thiserror = "1.0"
wgpu = { version = "0.12", features = ["spirv"] }
derive-deref-rs = "0.1"
pi_assets = "0.7"
# pi_assets = "0.1"
# pi_res_loader = {  git = "https://github.com/GaiaWorld/pi_res_loader.git" }
# pi_res_loader = { path = "../../../pi_res_loader" }
# pi_res = { path = "../../../pi_res" }
# pi_res_macros = { path = "../../../pi_res/macros" }

guillotiere = {version="0.6"}
smallvec="1.8"
lazy_static="1.4"
pi_atom = "0.1"

pi_ecs = { git = "https://github.com/GaiaWorld/pi_ecs.git" }
pi_hal={git="https://github.com/GaiaWorld/pi_hal.git"}

# [patch.crates-io]
# pi_ecs = { path = "../../../pi_ecs" }
