[package]
name = "pi_render"
version = "0.1.0"
authors = ["moyy <moyy@gmail.com>"]
edition = "2021"
description = "Renderer for PI Engine"
repository = "https://github.com/GaiaWorld/pi_render"
license = "MIT OR Apache-2.0"
keywords = ["pi"]

[features]

[dependencies]
pi_crevice = {path = "../pi_crevice"}
pi_ecs = {path = "../../../pi_ecs"}
futures-lite = "1.4"
log = "0.4"
naga = { version = "0.8", features = ["glsl-in", "spv-in", "spv-out", "wgsl-in", "wgsl-out"] }
raw-window-handle = "0.4"
wgpu = "0.12"


